\set ON_ERROR_STOP on

DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS suppliers CASCADE;
DROP TABLE IF EXISTS pickup_points CASCADE;
DROP TABLE IF EXISTS manufacturers CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE roles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE suppliers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE
);

CREATE TABLE pickup_points (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address varchar(300) NOT NULL
);

CREATE TABLE categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE
);

CREATE TABLE manufacturers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE
);

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(150) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    full_name varchar(250) NOT NULL,
    role_id integer NOT NULL REFERENCES roles(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE products (
    article varchar(20) PRIMARY KEY,
    name varchar(200) NOT NULL,
    unit varchar(20) NOT NULL,
    price numeric(12, 2) NOT NULL CHECK (price >= 0),
    category_id integer NOT NULL REFERENCES categories(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    manufacturer_id integer NOT NULL REFERENCES manufacturers(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    supplier_id integer NOT NULL REFERENCES suppliers(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    discount_percent integer NOT NULL DEFAULT 0 CHECK (discount_percent BETWEEN 0 AND 100),
    stock_quantity integer NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    description text NULL,
    photo_path varchar(260) NULL
);

CREATE TABLE orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id integer NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    pickup_point_id integer NOT NULL REFERENCES pickup_points(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    order_date date NOT NULL,
    delivery_date date NOT NULL,
    status varchar(50) NOT NULL,
    pickup_code varchar(20) NOT NULL UNIQUE,
    CONSTRAINT orders_delivery_after_order CHECK (delivery_date >= order_date)
);

CREATE TABLE order_items (
    order_id integer NOT NULL REFERENCES orders(id) ON UPDATE CASCADE ON DELETE CASCADE,
    product_article varchar(20) NOT NULL REFERENCES products(article) ON UPDATE CASCADE ON DELETE RESTRICT,
    quantity integer NOT NULL CHECK (quantity > 0),
    PRIMARY KEY (order_id, product_article)
);

CREATE INDEX ix_users_role_id ON users(role_id);
CREATE INDEX ix_products_category_id ON products(category_id);
CREATE INDEX ix_products_manufacturer_id ON products(manufacturer_id);
CREATE INDEX ix_products_supplier_id ON products(supplier_id);
CREATE INDEX ix_orders_client_id ON orders(client_id);
CREATE INDEX ix_orders_pickup_point_id ON orders(pickup_point_id);
CREATE INDEX ix_order_items_product_article ON order_items(product_article);

ALTER TABLE roles OWNER TO app;
ALTER TABLE suppliers OWNER TO app;
ALTER TABLE pickup_points OWNER TO app;
ALTER TABLE categories OWNER TO app;
ALTER TABLE manufacturers OWNER TO app;
ALTER TABLE users OWNER TO app;
ALTER TABLE products OWNER TO app;
ALTER TABLE orders OWNER TO app;
ALTER TABLE order_items OWNER TO app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app;
